### ISSUE TITLE
Preserve data from relationships

### ISSUE THREAD

**Issue by mrkmiller** [mysidewalk/jsonapi-parse#5]
I have a relationship which returns some data in it. This data is not preserved and merged with the data from the resulting "includes".
```javascript
"relationships": {
  "field_primary_image": {
    "data": {
      "type": "file--file",
      "id": "1234",
      "meta": {
        "alt": "My alt text",
        "title": "",
        "width": "1920",
        "height": "1080"
      }
    }
  }
}
```
The resulting `field_primary_image` contains the file/image data from the "includes" but does not have the `meta` data from the original relationships object with my alt text.

**Comment by pjfreeze** [comment]
Hey @mrkmiller -

I was doing some reading up on the specifications descriptions of ["meta objects"](http://jsonapi.org/format/#document-meta) and ran into some complications because of how frequently it can appear in the document.

- [Resource Objects](http://jsonapi.org/format/#document-resource-objects)
- [Resource Identifier Objects](http://jsonapi.org/format/#document-resource-identifier-objects)
- [Relationship Objects](http://jsonapi.org/format/#document-resource-object-relationships)
- [Top-level](http://jsonapi.org/format/#document-top-level)

In your example you show the "meta object" on a single "resource identifier object" within a member of the "relationship object" (e.g. `data[0].relationships.field_primary_image.data.meta`). A "meta object" is also supported on each "relationship object" within the relationships member (e.g. `relationships.field_primary_image.meta`). And another "meta object" is supported on each "resource object" within the top-level `data` or `included` members.

**With all of the possible locations of "meta objects", where would you expect them to be placed in the parsed result?**

Specifically, how would you handle the collision of a "meta object" on the general relationship (`data[0].relationships.field_primary_image.meta`), the relationship's "resource identifier object"'s "meta object"(s) (`data[0].relationships.field_primary_image.data.meta`), and the included "resource object"'s "meta object (`included[0].meta`).

Because all three of those could likely contain similar information, it makes it hard to know if and/or how to keep all of the original data in tact.

**Comment by mrkmiller** [comment]
Hmmm... I honestly have no idea... That's a tough one. As much as I would like to have them all merged into a single level I can see the possibility of wrecking/overwriting data.
One possible idea is to do an output with something like
```
"field_primary_image": {
    "meta": {
      "item 1": "meta value from the general relationship",
      "item 2": "meta value from the general relationship",
      "relationships": {
        "item": "meta values from the relationship's resource identifier object"
      },
      "included": {
        "item": "meta value from the included resource object"
      }
    }
  }
```
It's not pretty, but at least data is kept intact and people can possibly reason about where things initially came from. I don't know if is confusing using the names "relationships" and "included" since they mean something very specific in the spec.

**Comment by pjfreeze** [comment]
Hmm, I'm not sure I follow where the "item" keys came from. Were you using those as examples of keys from actual meta objects?

---

Based on reading your message and thinking about this, I'm leaning towards the following:

- Meta information is kept only where it is added (see `is_best_friend` example)
- Meta information from source identifiers get added to that resource, not the resource that pointed to the identifier (See `is_best_friend` example)
- Meta objects themselves store the description/path from where it came from (see `friend_count` example)
- Meta information included on either the root "data" member or any "included" member should be set on all instances (See `age` examples)

I think this keeps the meta information handy where _I think_ it would make sense, based on the context/placement of the meta object. E.g. a meta object on the relationship, not the related resource is pertinent to the resource describing the relationship.

I was also trying to avoid using really complicated keys, e.g. `['relationships.friends.meta']` or `['relationships.friends[0].meta']`.

## Proposed outcome

(_I think this is close, if not exactly what you have suggested above._)

**Input**

``` javascript
{
  "data": {
    "id": "1",
    "type": "person",
    "attributes": {
      "full_name": "Jane Doe"
    },
    "meta": {
      "age": 11
    },
    "relationships": {
      "friends": {
        "data": [
          {
            "id": "3",
            "type": "person",
            "meta": {
              "is_best_friend": false
            }
          }
        ],
        "meta": {
          "friend_count": 5
        }
      }
    }
  },
  "included": {
    "id": "3",
    "type": "person",
    "attributes": {
      "full_name": "John Doe"
    },
    "meta": {
      "age": 10
    }
  }
}
```


**Output**

``` javascript
{
  "data": {
    "id": "1",
    "type": "person",
    "full_name": "Jane Doe",
    "meta": {
      "age": 11,
      "relationships": {
        "friends": {
          "friend_count": 5
        }
      }
    },
    "friends": [
      {
        "id": "3",
        "type": "person",
        "full_name": "John Doe",
        "meta": {
          "age": 10,
          "relationship": {
            "is_best_friend": false
          }
        }
      }
    ]
  },
  "included": [
    {
      "id": "3",
      "type": "person",
      "full_name": "John Doe",
      "meta": {
        "age": 10
      }
    }
  ]
}
```

P.S. this might also be relevant to @adborden based on our discussion of #2 and using `meta` for a different purpose.

**Comment by mrkmiller** [comment]
Sorry for the confusion on the "item" keys. Those were just arbitrary keys from different meta objects. It would have helped if I showed the input as well.

So I think what you have looks good. Output for `data.meta.relationships.friends.friend_count` might be a little verbose, but I think it's still coherent. I don't have anything better to offer for that one.

**Comment by pjfreeze** [comment]
@mrkmiller

Hey - I got a working version of this pushed to a branch, `5-missing-meta-properties`. Before releasing this change, I want to get a few test cases written. That may take a couple of days, so I wanted to be sure you could use this if you needed it more immediately.

**Comment by mrkmiller** [comment]
I found one issue throwing an error. I added a PR here #7. Other than that it seems to work well.

**Comment by pjfreeze** [comment]
Awesome, merged that in; hoping to tackle writing a few tests for those changes today

**Comment by pjfreeze** [comment]
Found some funky stuff where relationship specific meta was appearing in all instances of that record within the document. Wrote a test to try to prevent it and moved the change you made to a different file to better handle context specific meta objects.

Wrote a handful of other tests; hoping to circle back this afternoon and write a few more before I merge and release this.
